[files]
extend-exclude = [
    "image/jpegrescan/",
    "image/packjpg/",
    "mail/spam/21_KAM.cf",
    "monitoring/aruba-serclient.deb/",
    "monitoring/hdd-seeker/",
    "monitoring/watcher/",
    "mysql/mysqltuner/",
    "security/ca/ca-web/text",
    "security/password2remember_hu.txt",
    "webserver/server-configs-nginx/"
]

[default.extend-words]

[default.extend-identifiers]
# False positives
rsource = "rsource"
helo = "helo"
referer = "referer"
responsable = "responsable"
# https://pkg.go.dev/os#pkg-constants
"O_WRONLY" = "O_WRONLY"
# Typos
contiguities = "continuities"
intension = "intention"
intensional = "intentional"
intensionally = "intentionally"
intensionaly = "intentionally"
pervious = "previous"
perviously = "previously"
