[files]
extend-exclude = [
    "mail/courier-pythonfilter/",
    "mail/msglint/",
    "mysql/mysqltuner/",
    "webserver/server-configs-nginx/",
    ".git/",
    "Intercom.md", # HU
    "mail/mx-check/disposable-email/", # Domain lists
    "mail/mx-check/disposable-mx.list", # Domain list
    "mail/spam/21_KAM.cf", # Spam words
    "mail/spammer.dnsbl/spammer.dnsbl.zone", # Network names
    "monitoring/README.md", # Contains router names
    "package/apt-sources/google-cloud-sdk.list", # Fingerprint
    "package/docker-backport-goaccess.sh", # base64
    "package/quicklz-build.sh", # base64
    "package/s3ql-3C4E599F.asc", # GPG key
    "repo/debian/dists/", # APT repository
    "security/ca/ca-web/text", # SSL certificate
    "security/myattackers-ipsets/ipset/", # International names
    "security/password2remember_hu.txt", # HU
]
ignore-hidden = false

[default]
extend-ignore-re = [
    " fo=1",
    "\\|shs\\|",
    "\\$!ba;",
    ";ba'",
    "/bin/\\(ba\\)\\?sh",
    "-MISSy",
    "\\^fpr:::::::::",
    "   ue   End underlining",
    "PIPE_PASSWORD='\\S+'",
    "\\|ignor\\[ei\\]",
    "nmap -n -Pn",
    "\\|og\\[agv\\]",
]

[default.extend-words]
#"wht"="wht"
"hd"="hd"
# False positives
"bck" = "bck"
"eof" = "eof"
"helo" = "helo"
"chello" = "chello"
"lst" = "lst"
"rsource" = "rsource"
"referer" = "referer"
"seeked" = "seeked"

# Typos
"contiguities" = "continuities"
"intension" = "intention"
"intensional" = "intentional"
"intensionally" = "intentionally"
"intensionaly" = "intentionally"
"pervious" = "previous"
"perviously" = "previously"
"covert" = "convert"

[default.extend-identifiers]
# False positives
"ogPipe" = "ogPipe"
"ogShow" = "ogShow"
# https://manpages.debian.org/bookworm/manpages-dev/open.2.en.html#File_access_mode
"O_WRONLY" = "O_WRONLY"
"SSL_CK_DES_192_EDE3_CBC_WITH_MD5" = "SSL_CK_DES_192_EDE3_CBC_WITH_MD5"
"LESS_TERMCAP_ue" = "LESS_TERMCAP_ue"

# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
