# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Docs"

on:  # yamllint disable-line rule:truthy
    # pull_request:
    #     paths:
    #     - "**/*.md"
    #     - "markdown-link-check.json"
    # push:
    #     branches:
    #     - "master"
    #     paths:
    #     - "**/*.md"
    #     - "markdown-link-check.json"
    workflow_dispatch: null
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    links:
        name: "Links"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3.5.3"
        -
            name: "Run Lychee"
            uses: "lycheeverse/lychee-action@v1.8.0"
            with:
                output: "${{ runner.temp }}/lychee/out.md"
                fail: true
